import tkinter as tk
def add_numbers():
    result = float(entry1.get()) + float(entry2.get())
    label_result.config(text=f"Result: {result}")
root = tk.Tk()
root.title("Add Two Numbers")
label1 = tk.Label(root, text="Enter number 1:")
label1.pack()
entry1 = tk.Entry(root)
entry1.pack()
label2 = tk.Label(root, text="Enter number 2:")
label2.pack()
entry2 = tk.Entry(root)
entry2.pack()
button = tk.Button(root, text="Add", command=add_numbers)
button.pack()
label_result = tk.Label(root, text="Result:")
label_result.pack()
root.mainloop()
